spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ftracker
    username: user
    password: geheim
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update   # Entwicklung; besser "validate" oder Migrationstool in Prod
    show-sql: true
    properties:
      hibernate.format_sql: true
    open-in-view: false
